apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Values.imageodoo }}
  name: {{ .Values.imageodoo }}
spec:
  replicas: 1
  selector:
    app: {{ .Values.imageodoo }}
    deploymentconfig: {{ .Values.imageodoo }}
  template:
    metadata:
      labels:
        app: {{ .Values.imageodoo }}
        deploymentconfig: {{ .Values.imageodoo }}
    spec:
      containers:
        - image: 'docker-gitlab.sudokeys.com/infra/docker-odoo:11.0.1'
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: {{ .Values.imageodoo }}
      dnsPolicy: ClusterFirst
      restartPolicy: {{ .Values.restartPolicy }}


