apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: storage-{{ .Values.mariadbname }}
spec:
 accessModes:
  - {{ .Values.accessmodesmariadb }}
 resources:
   requests:
        storage: {{ .Values.storagemariadb }}
storageClassName: {{ .Values.storageClassName }}

---

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Values.wordpressname }}
  name: {{ .Values.wordpressname }}
spec:
  replicas: 1
  selector:
    app: {{ .Values.wordpressname }}
    deploymentconfig: {{ .Values.wordpressname }}
  template:
    metadata:
      labels:
        app: {{ .Values.wordpressname }}
        deploymentconfig: {{ .Values.wordpressname }}
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.mariadbname }}:3306
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpressname }}-secret
                  key: password
          image: {{ .Values.imagewordpress }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: {{ .Values.wordpressname }}
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: {{ .Values.restartPolicy }}
      
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.wordpressname }}
  name: {{ .Values.wordpressname }}
spec:
  host: {{ .Values.host }}
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: {{ .Values.wordpressname }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
      host: {{ .Values.host }}
      routerName: router
wildcardPolicy: None

---

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Values.mariadbname }}
  name: {{ .Values.mariadbname }}
spec:
  replicas: 1
  selector:
    app: {{ .Values.mariadbname }}
    deploymentconfig: {{ .Values.mariadbname }}
  template:
    metadata:
      labels:
        app: {{ .Values.mariadbname }}
        deploymentconfig: {{ .Values.mariadbname }}
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpressname }}-secret
                  key: password
          image: library/mariadb
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: {{ .Values.mariadbname }}
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              readOnly: false
              name: volume-{{ .Values.mariadbname }}
      volumes:
        - name: volume-{{ .Values.mariadbname }}
          persistentVolumeClaim:
            claimName: storage-{{ .Values.mariadbname }}
      restartPolicy: {{ .Values.restartPolicy }}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.mariadbname }}
  name: {{ .Values.mariadbname }}
spec:
  clusterIP: None
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    deploymentconfig: {{ .Values.mariadbname }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.wordpressname }}
  name: {{ .Values.wordpressname }}
spec:
  clusterIP: None
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    deploymentconfig: {{ .Values.wordpressname }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

--- 

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wordpressname }}-secret
data:
  password: {{ .Values.password }}
