apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mariadbstorage
spec:
 accessModes:
  - {{ .Values.accessmodesmariadb }}
 resources:
   requests:
        storage: {{ .Values.storagemariadb }}
storageClassName: {{ .Values.storageClassName }}

---

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    app: wordpress
    deploymentconfig: wordpress
  template:
    metadata:
      labels:
        app: wordpress
        deploymentconfig: wordpress
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: "mariadb:3306"
            - name: WORDPRESS_DB_USER
              value: "root"
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.password }}
          image: {{ .Values.imagewordpress }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: wordpress
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: {{ .Values.restartPolicy }}
      
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  host: {{ .Values.host }}
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: wordpress
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
      host: {{ .Values.host }}
      routerName: router
wildcardPolicy: None

---

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    app: mariadb
    deploymentconfig: mariadb
  template:
    metadata:
      labels:
        app: mariadb
        deploymentconfig: mariadb
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.password }}
          image: library/mariadb
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: mariadb
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              readOnly: false
              name: volumebd
      volumes:
        - name: volumebd
          persistentVolumeClaim:
            claimName: mariadbstorage
      restartPolicy: {{ .Values.restartPolicy }}
