apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
data:
  password: {{ .Values.password }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mariadbstorage
spec:
 accessModes:
  - {{ .Values.accessmodesmariadb }}
 resources:
   requests:
        storage: {{ .Values.storagemariadb }}
storageClassName: {{ .Values.storageClassName }}

---

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Values.wordpressname }}
  name: {{ .Values.wordpressname }}
spec:
  selector:
    app: {{ .Values.wordpressname }}
    deploymentconfig: {{ .Values.wordpressname }}
  template:
    metadata:
      labels:
        app: {{ .Values.wordpressname }}
        deploymentconfig: {{ .Values.wordpressname }}
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: "mariadb:3306"
            - name: WORDPRESS_DB_USER
              value: "root"
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: password
          image: {{ .Values.imagewordpress }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: {{ .Values.wordpressname }}
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: {{ .Values.restartPolicy }}
      
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  host: {{ .Values.host }}
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: wordpress
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
      host: {{ .Values.host }}
      routerName: router
wildcardPolicy: None

---

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: {{ .Values.mariadbname }}
  name: {{ .Values.mariadbname }}
spec:
  selector:
    app: {{ .Values.mariadbname }}
    deploymentconfig: {{ .Values.mariadbname }}
  template:
    metadata:
      labels:
        app: {{ .Values.mariadbname }}
        deploymentconfig: {{ .Values.mariadbname }}
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: password
          image: library/mariadb
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: {{ .Values.mariadbname }}
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              readOnly: false
              name: {{ .Values.mariadbname }}
      volumes:
        - name: {{ .Values.mariadbname }}
          persistentVolumeClaim:
            claimName: mariadbstorage
      restartPolicy: {{ .Values.restartPolicy }}
