apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  host: {{ .Values.host }}
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: wordpress
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
      host: {{ .Values.host }}
      routerName: router
      wildcardPolicy: None
