apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mariadbstrorage
spec:
 accessModes:
  - {{ .Values.accessmodesmariadb }}
 resources:
   requests:
        storage: {{ .Values.storagemariadb }}
storageClassName: {{ .Values.storageClassName }}

---

apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb
    image: mariadb
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: {{ .Values.password }}
    volumeMounts:
    - name: mariadbstorage
      mountPath: /var/lib/mysql
      readOnly: false
  volumes:
  - name: mariadbstorage
    persistentVolumeClaim:
      claimName: mariadbstorage
  restartPolicy: {{ .Values.restartPolicy }}

---

apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordperss
spec:
  containers:
  - name: wordpress
    image: {{ .Values.imagewordpress }}
    imagePullPolicy: {{ .Values.pullPolicy }}
    env:
    - name: WORDPRESS_DB_HOST
      value: "mariadb:3306"
      ports:
      - name: http
        containerPort: 80
        protocol: TCP
  restartPolicy: {{ .Values.restartPolicy }}
      
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  host: {{ .Values.host }}
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: wordpress
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
      host: {{ .Values.host }}
      routerName: router
wildcardPolicy: None
