apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: mariadb
        image: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.password }}
        volumeMounts:
        - name: mariadbstorage
          mountPath: /var/lib/mysql
          readOnly: false
        volumes:
        - name: mariadbstorage
          persistentVolumeClaim:
            claimName: mariadbstorage

      - name: wordpress
        image: {{ .Values.imagewordpress }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
        - name: WORDPRESS_DB_HOST
          value: "mariadb:3306"
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
      restartPolicy: {{ .Values.restartPolicy }}

