apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  # This shows how to use a simple value. This will look for a passed-in value called restartPolicy.
  restartPolicy: {{ .Values.restartPolicy }}
  containers:
  - name: nginxtest
    image: nginx
    imagePullPolicy: {{ .Values.image.pullPolicy }}
