apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mariadbstrorage
spec:
 accessModes:
  - {{ .Values.accessmodesmariadb }}
 resources:
   requests:
        storage: {{ .Values.storagemariadb }}
storageClassName: {{ .Values.storageClassName }}
