apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-{{ .Values.mariadbname }}
spec:
  accessModes:
  - {{ .Values.accessmodesmariadb }}
  capacity:
    storage: {{ .Values.storagemariadb }}
  hostPath:
    path: {{ .Values.path }}
  persistentVolumeReclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume{{ .Values.mariadbname }}
spec:
  accessModes:
  - {{ .Values.accessmodesmariadb }}
  resources:
    requests:
      storage: {{ .Values.storagemariadb }}
  storageClassName: ""
  volumeName: volume-{{ .Values.mariadbname }}

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: {{ .Values.wordpressname }}
  name: {{ .Values.wordpressname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.wordpressname }}
  template:
    metadata:
      labels:
        app: {{ .Values.wordpressname }}
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.mariadbname }}:3306
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: password
          image: {{ .Values.imagewordpress }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: {{ .Values.wordpressname }}
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: {{ .Values.restartPolicy }}
      
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wordpressname }}
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: ingress-978081268d311422b8c1011304b8794a
          servicePort: 80
status:
  loadBalancer:
    ingress:
    - ip: 10.4.3.10
    - ip: 10.4.3.14
    - ip: 10.4.3.15


---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: {{ .Values.mariadbname }}
  name: {{ .Values.mariadbname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mariadbname }}
  template:
    metadata:
      labels:
        app: {{ .Values.mariadbname }}
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: password
          image: library/mariadb
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: {{ .Values.mariadbname }}
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              readOnly: false
              name: volumedata
      volumes:
        - name: volumedata
          persistentVolumeClaim:
            claimName: volume{{ .Values.mariadbname }}
      restartPolicy: {{ .Values.restartPolicy }}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.mariadbname }}
  name: {{ .Values.mariadbname }}
spec:
  clusterIP: None
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    workloadID_{{ .Values.mariadbname }}: "true"
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.wordpressname }}
  name: {{ .Values.wordpressname }}
spec:
  clusterIP: None
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    deployment: {{ .Values.wordpressname }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

--- 

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wordpressname }}-secret
data:
  password: {{ .Values.password }}
