apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpressvolume
spec:
  accessModes:
  - {{ .Values.accessmodes }}
  capacity:
    storage: {{ .Values.storage }}
  hostPath:
    path: {{ .Values.path }}
  persistentVolumeReclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volumemaria
spec:
  accessModes:
  - {{ .Values.accessmodes }}
  resources:
    requests:
      storage: {{ .Values.storage }}
  storageClassName: ""
  volumeName: volumewordpress

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: "mariadb:3306"
            - name: WORDPRESS_DB_HOST
              value: "root"
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.password }}
          image: {{ .Values.imagewordpress }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: wordpress
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: {{ .Values.restartPolicy }}
      
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: ingress-978081268d311422b8c1011304b8794a
          servicePort: 80
status:
  loadBalancer:
    ingress:
    - ip: 10.4.3.10
    - ip: 10.4.3.14
    - ip: 10.4.3.15


---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.password }}
          image: library/mariadb
          imagePullPolicy: {{ .Values.pullPolicy }}
          name: mariadb
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              readOnly: false
              name: volumedata
      volumes:
        - name: volumedata
          persistentVolumeClaim:
            claimName: volumemaria
      restartPolicy: {{ .Values.restartPolicy }}
